kind: Service
apiVersion: v1
metadata:
  name: app-three
  labels:
    p2: app3
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    p2: app3
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-three
  annotations:
    IOT/owner: "m&m's"
  labels:
    p2: app3
spec:
  selector:
    matchLabels:
      p2: app3
  template:
    metadata:
      labels:
        p2: app3
    spec:
      containers:
      - name: app-three-container
        image: paulbouwer/hello-kubernetes:1.9
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: MESSAGE
            value: "Hello from app3."
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 4
          periodSeconds: 30
        securityContext:
          readOnlyRootFilesystem: true
