apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    app: app2
spec:
  rules:
  - http:
      paths:
      - path: /sudoku
        pathType: Prefix
        backend:
          service:
            name: app-two
            port:
              number: 443
  - host: app2.com
    http:
      paths:
      - path: /sudoku
        pathType: Prefix
        backend:
          service:
            name: app-two
            port:
              number: 443