apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
  annotations:
    IOT/owner: "m&m's"
---
kind: Service
apiVersion: v1
metadata:
  name: gitlab
  namespace: gitlab
  annotations:
    IOT/owner: "m&m's"
  labels:
    iot: bonus
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    iot: bonus
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gitlab
  namespace: gitlab
  annotations:
    IOT/owner: "m&m's"
  labels:
    iot: bonus
spec:
  selector:
    matchLabels:
      iot: bonus
  template:
    metadata:
      labels:
        iot: bonus
    spec:
      containers:
      - name: gitlab-container
        image: mdulcie/inception-of-things-42-21-bonus-gitlab:v3
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bonus-ingress
  namespace: gitlab
  annotations:
    IOT/owner: "m&m's"
  labels:
    iot: bonus
spec:
  rules:
  - host: mygitlab.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitlab
            port:
              number: 80
