# -*- mode: ruby -*-
# vi: set ft=ruby :

# Server datas
NODE_S_NAME     =   "mdulcieS"
NODE_S_IP       =   "192.168.56.110"

# Generate token
require 'openssl'
require 'digest/md5'
TOKEN = Digest::MD5.hexdigest(OpenSSL::Random.random_bytes(32))

#  k3s configs 
# (the configs must be in the same folder as the Vagrantfile)
K3S_CONFIG_PATH =   "/vagrant/confs/"

# Configure
Vagrant.configure("2") do |config|
  config.vm.box     = "CentOS_official_site_OS"
  # config.vm.box_url = "https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Vagrant-8.4.2105-20210603.0.x86_64.vagrant-virtualbox.box"
  config.vm.box_url = "https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-Vagrant-9-20221206.0.x86_64.vagrant-virtualbox.box.SHA256SUM"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus   = 2
  end

  config.vm.define NODE_S_NAME do |nodeS|
    nodeS.vm.hostname = NODE_S_NAME
    nodeS.vm.network "private_network", ip: NODE_S_IP
    nodeS.vm.provider "virtualbox" do |vb|
      vb.name = NODE_S_NAME
    end
    nodeS.vm.provision "shell", privileged: true,
      path: "scripts/run.sh", args: [NODE_S_IP, TOKEN, K3S_CONFIG_PATH]
  end

end
