# -*- mode: ruby -*-
# vi: set ft=ruby :

# Server datas
NODE_S_NAME  =   "mdulcieS"
NODE_S_IP    =   "192.168.56.110"

# Server Worker datas
NODE_SW_NAME =   "mdulcieSW"
NODE_SW_IP   =   "192.168.56.111"

# Generate token
require 'openssl'
require 'digest/md5'
TOKEN = Digest::MD5.hexdigest(OpenSSL::Random.random_bytes(32))

# environmental-variables
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

# Configure
Vagrant.configure("2") do |config|
  config.vm.box     = "CentOS_official_site_OS"
  config.vm.box_url = "https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Vagrant-8.4.2105-20210603.0.x86_64.vagrant-virtualbox.box"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus   = 1
  end

  config.vm.define NODE_S_NAME do |nodeS|
    nodeS.vm.hostname = NODE_S_NAME
    nodeS.vm.network "private_network", ip: NODE_S_IP
    nodeS.vm.provider "virtualbox" do |vb|
      vb.name = NODE_S_NAME
    end
    nodeS.vm.provision "shell", privileged: true,
      path: "scripts/runS.sh", args: [NODE_S_IP, TOKEN]
  end

  config.vm.define NODE_SW_NAME do |nodeSW|
    nodeSW.vm.hostname = NODE_SW_NAME
    nodeSW.vm.network "private_network", ip: NODE_SW_IP
    nodeSW.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", NODE_SW_NAME]
    end
    nodeSW.vm.provision "shell", privileged: true,
      path: "scripts/runSW.sh", args: [NODE_S_IP, TOKEN]
  end
end
